(deftheme noir
  "Created 2023-11-13.")

(custom-theme-set-variables
 'noir
 '(connection-local-criteria-alist '(((:application tramp) tramp-connection-local-default-system-profile tramp-connection-local-default-shell-profile)))
 '(connection-local-profile-alist '((tramp-connection-local-darwin-ps-profile (tramp-process-attributes-ps-args "-acxww" "-o" "pid,uid,user,gid,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state=abcde" "-o" "ppid,pgid,sess,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etime,pcpu,pmem,args") (tramp-process-attributes-ps-format (pid . number) (euid . number) (user . string) (egid . number) (comm . 52) (state . 5) (ppid . number) (pgrp . number) (sess . number) (ttname . string) (tpgid . number) (minflt . number) (majflt . number) (time . tramp-ps-time) (pri . number) (nice . number) (vsize . number) (rss . number) (etime . tramp-ps-time) (pcpu . number) (pmem . number) (args))) (tramp-connection-local-busybox-ps-profile (tramp-process-attributes-ps-args "-o" "pid,user,group,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "stat=abcde" "-o" "ppid,pgid,tty,time,nice,etime,args") (tramp-process-attributes-ps-format (pid . number) (user . string) (group . string) (comm . 52) (state . 5) (ppid . number) (pgrp . number) (ttname . string) (time . tramp-ps-time) (nice . number) (etime . tramp-ps-time) (args))) (tramp-connection-local-bsd-ps-profile (tramp-process-attributes-ps-args "-acxww" "-o" "pid,euid,user,egid,egroup,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state,ppid,pgid,sid,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etimes,pcpu,pmem,args") (tramp-process-attributes-ps-format (pid . number) (euid . number) (user . string) (egid . number) (group . string) (comm . 52) (state . string) (ppid . number) (pgrp . number) (sess . number) (ttname . string) (tpgid . number) (minflt . number) (majflt . number) (time . tramp-ps-time) (pri . number) (nice . number) (vsize . number) (rss . number) (etime . number) (pcpu . number) (pmem . number) (args))) (tramp-connection-local-default-shell-profile (shell-file-name . "/bin/sh") (shell-command-switch . "-c")) (tramp-connection-local-default-system-profile (path-separator . ":") (null-device . "/dev/null")))))

(custom-theme-set-faces
 'noir
 '(fringe ((t (:background "black"))))
 '(internal-border ((t (:background "black"))))
 '(cursor ((((class color) (min-colors 89)) (:background "thistle"))))
 '(error ((((class color) (min-colors 89)) (:foreground "salmon1"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "orange"))))
 '(success ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "black"
							    :box (:line-width 2)))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "dark green"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "dark goldenrod"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "SpringGreen4"))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "ForestGreen"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "white" :background "dark green"))))
 '(region ((((class color) (min-colors 89)) (:foreground "white" :background "dark green"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "dark slate gray"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "white" :background "dark goldenrod"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "gray25"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightSteelBlue"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "SpringGreen3"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "turquoise"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "white"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "aquamarine"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "cyan"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "dark cyan"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:weight normal :foreground "yellow green"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "pale turquoise"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "dark sea green"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "dark turquoise"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "pale turquoise"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "SpringGreen3"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "deep sky blue"))))
 '(realgud-overlay-arrow1 ((((class color) (min-colors 89)) (:foreground "SpringGreen3"))))
 '(realgud-overlay-arrow2 ((((class color) (min-colors 89)) (:foreground "white"))))
 '(realgud-overlay-arrow3 ((((class color) (min-colors 89)) (:foreground "wheat"))))
 '(realgud-bp-enabled-face ((((class color) (min-colors 89)) (:inherit error))))
 '(realgud-bp-disabled-face ((((class color) (min-colors 89)) (:foreground "dark slate gray"))))
 '(realgud-bp-line-enabled-face ((((class color) (min-colors 89)) (:underline "SpringGreen3"))))
 '(realgud-bp-line-disabled-face ((((class color) (min-colors 89)) (:underline "salmon"))))
 '(realgud-file-name ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(realgud-line-number ((((class color) (min-colors 89)) (:foreground "dark cyan"))))
 '(realgud-backtrace-number ((((class color) (min-colors 89)) (:foreground "dark cyan" :weight bold))))
 '(default ((((class color) (min-colors 89)) (:foreground "wheat" :background "black")))))

(provide-theme 'noir)
